server:
  error:
    include-stacktrace: on_param
    whitelabel:
      enabled: false


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vlpt?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    hiddenmethod:
      filter:
        enabled: true
